"""Ajout du champ mac_address au modèle Plant

Revision ID: 62e4a9197ecc
Revises: 
Create Date: 2025-04-09 10:12:33.047574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62e4a9197ecc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mac_address', sa.String(length=100), nullable=False, server_default="UNKNOWN"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plant', schema=None) as batch_op:
        batch_op.drop_column('mac_address')

    # ### end Alembic commands ###
